force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <description>Something to be done</description>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status can have 3 state</description>
    <inlineHelpText>Please, choose status of yot todo</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to Take</fullName>
                <default>true</default>
                <label>Ready to Take</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ToDo__c/recordTypes/Later.recordType-meta.xml
<RecordType>
    <fullName>Later</fullName>
    <active>true</active>
    <label>Later</label>
</RecordType>

force-app/main/default/objects/ToDo__c/recordTypes/Today.recordType-meta.xml
<RecordType>
    <fullName>Today</fullName>
    <active>true</active>
    <label>Today</label>
</RecordType>

force-app/main/default/objects/ToDo__c/recordTypes/Tomorrow.recordType-meta.xml
<RecordType>
    <fullName>Tomorrow</fullName>
    <active>true</active>
    <label>Tomorrow</label>
</RecordType>

force-app/main/default/classes/ToDoFromEmailCreator.cls
public with sharing class ToDoFromEmailCreator {
	@InvocableMethod(label='Create ToDo from Case' description='Creates the ToDo with parameters with parameters specified in the description.' category='ToDo')
    public static void createToDos(List<String> descriptions) {
        List<ToDo__c> toDos = new List<ToDo__c>();
        List<RecordType> recordTypes = [SELECT Id, Name, SobjectType FROM RecordType WHERE SobjectType = 'ToDo__c'];
        for (String description: descriptions) {
            ToDo__c toDo = getToDoFromDescription(description, recordTypes);
            if (toDo.Name != null)  {
                toDos.add(toDo);    
            }
        }
        if (toDos.size() != 0) {
            insert toDos;    
        }
    }
    
    @testVisible
    private static ToDo__c getToDoFromDescription(String description, List<RecordType> recordTypes) {
        String[] stringParameters = description.split('\n');        
        if (stringParameters.size() == 3) {
            ToDo__c toDo = new ToDo__c(Name = stringParameters[0]);
            toDo.Status__c = getStatusFromParameter(stringParameters[1]);
            toDo.RecordTypeId = getRecordTypeId(stringParameters[2], recordTypes);
            return toDo;
        } else {
            return new ToDo__c();    
        }
    }
    
    @testVisible
    private static String getStatusFromParameter(String parameter) {
        if ((parameter == 'In Progress') || (parameter == 'In progress') || (parameter == 'in progress')) {
            return 'In Progress';
        } else if ((parameter == 'Done') || (parameter == 'done')) {
            return 'Done';
        } else {
            return 'Ready to Take';
        }
    }
    
    @testVisible
    private static Id getRecordTypeId(String parameter, List<RecordType> recordTypes) {
        Id laterId = null;
        for (RecordType recordType: recordTypes) {
            if ((recordType.Name == 'Today') && ((parameter == 'today') || (parameter == 'Today'))) {
                return recordType.Id;
            }
            if ((recordType.Name == 'Tomorrow') && ((parameter == 'tomorrow') || (parameter == 'Tomorrow'))) {
                return recordType.Id;
            }
            if (recordType.Name == 'Later') {
                laterId = recordType.Id;
                if ((parameter == 'later') || (parameter == 'Later')) {
                    return laterId;
                }
            }    
        }
        return laterId;
    }
}