force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <description>Something to be done</description>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status can have 3 state</description>
    <inlineHelpText>Please, choose status of yot todo</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to Take</fullName>
                <default>true</default>
                <label>Ready to Take</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ToDoController.cls
public with sharing class ToDoController {
    @AuraEnabled(cacheable=true)
    public static List<ToDo__c> getAllToDos() {
        return [SELECT Id, Name, Status__c, RecordTypeId FROM ToDo__c WITH SECURITY_ENFORCED];
    }
    
    @AuraEnabled(cacheable=true)
    public static ToDo__c getToDoByName(String name) {
        List<ToDo__c> toDos = [SELECT Id, Name, Status__c, RecordTypeId FROM ToDo__c WHERE name = :name WITH SECURITY_ENFORCED];
        if (toDos.size() >= 1) {
            return toDos[0];
        } else {
            return new ToDo__c();
        }
    }
}