force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <description>Something to be done</description>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/recordTypes/Today.recordType-meta.xml
<RecordType>
    <fullName>Today</fullName>
    <active>true</active>
    <label>Today</label>
</RecordType>

force-app/main/default/objects/ToDo_Cleaning_Setting__mdt/ToDo_Cleaning_Setting__mdt.object-meta.xml
<CustomObject>
    <description>How long does it take to clear old ToDos?</description>
    <label>ToDo Cleaning Setting</label>
    <pluralLabel>ToDo Cleaning Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ToDo_Cleaning_Setting__mdt/fields/Number_of_Months__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Months__c</fullName>
    <defaultValue>3</defaultValue>
    <label>Number of Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OldToDosIterable.cls
public with sharing class OldToDosIterable implements Iterable<ToDo__c> {
    public Iterator<ToDo__c> iterator() {
        ToDoIterator iterator;
        List<ToDo_Cleaning_Setting__mdt> settings = [SELECT Id, DeveloperName, Number_of_Months__c FROM ToDo_Cleaning_Setting__mdt];
        if (settings.size() > 0) {
            Date pastDate = Date.today() - ((365/12)*Integer.valueOf(settings[0].Number_of_Months__c));
            // Данный вариант раскомментировать при проведении тестов с целью проверки исполнения CleanOldToDos.execute
            // List<ToDo__c> toDos = [SELECT Name, CreatedDate FROM ToDo__c WHERE CreatedDate > :pastDate];
            List<ToDo__c> toDos = [SELECT Name, CreatedDate FROM ToDo__c WHERE CreatedDate <= :pastDate];
            iterator = new ToDoIterator(toDos);
        }
        return iterator;
    }
}