force-app/main/default/objects/Sub_ToDo__c/Sub_ToDo__c.object-meta.xml
<CustomObject>
    <description>Subtask for a big task</description>
    <label>Sub-ToDo</label>
    <nameField>
        <label>Sub-ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-ToDos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sub_ToDo__c/fields/ExtId__c.field-meta.xml
<CustomField>
    <fullName>ExtId__c</fullName>
    <label>ExtId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sub_ToDo__c/fields/Is_Done__c.field-meta.xml
<CustomField>
    <fullName>Is_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mission completed?)</description>
    <label>Is Done</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sub_ToDo__c/fields/ToDo__c.field-meta.xml
<CustomField>
    <fullName>ToDo__c</fullName>
    <description>To which task does</description>
    <label>ToDo</label>
    <referenceTo>ToDo__c</referenceTo>
    <relationshipLabel>Sub-ToDos</relationshipLabel>
    <relationshipName>Sub_ToDos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <description>Something to be done</description>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status can have 3 state</description>
    <inlineHelpText>Please, choose status of yot todo</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to Take</fullName>
                <default>true</default>
                <label>Ready to Take</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FutureToDoCallouts.cls
public with sharing class FutureToDoCallouts {
    @future(callout=true)
    public static void postToDo(List<Id> listId)
    {
        for (Id todoId : listId) {
            String todoJson = todoToJson(todoId);
            // callout post
            HttpResponse resp = ToDoRestCallouts.postToDo(todoJson);
        }
    }
    @future(callout=true)
    public static void putToDo(List<Id> listId)
    {
        for (Id todoId : listId) {
            String todoJson = todoToJson(todoId);
            // callout put
            HttpResponse resp = ToDoRestCallouts.putToDo(todoJson);
        }
    }
    @future(callout=true)
    public static void patchToDo(List<Id> listId)
    {
        for (Id todoId : listId) {
            ToDo__c todo = [SELECT Name, Status__c FROM ToDo__c WHERE Id = :todoId];
            // object serialization
            String todoJson = JSON.serialize(todo);
            // callout patch
            HttpResponse resp = ToDoRestCallouts.patchToDo(todoId, todoJson);
        }
    }
    @future(callout=true)
    public static void deleteToDo(List<Id> listId)
    {
        for (Id todoId : listId) {
            // callout delete
            HttpResponse resp = ToDoRestCallouts.deleteToDo(todoId);
        }
    }
    // helper
    static String todoToJson(String todoId) {
        ToDo__c todo = [SELECT Name, Status__c, ExtId__c, (SELECT Name, Is_Done__c, ToDo__c, ExtId__c  FROM Sub_ToDos__r) FROM ToDo__c WHERE Id = :todoId];
        String todoJson = JSON.serialize(todo);
        return todoJson;
    }
}