force-app/main/default/objects/Sub_ToDo__c/Sub_ToDo__c.object-meta.xml
<CustomObject>
    <description>Subtask for a big task</description>
    <label>Sub-ToDo</label>
    <nameField>
        <label>Sub-ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-ToDos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sub_ToDo__c/fields/Is_Done__c.field-meta.xml
<CustomField>
    <fullName>Is_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mission completed?)</description>
    <label>Is Done</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sub_ToDo__c/fields/ToDo__c.field-meta.xml
<CustomField>
    <fullName>ToDo__c</fullName>
    <description>To which task does</description>
    <label>ToDo</label>
    <referenceTo>ToDo__c</referenceTo>
    <relationshipLabel>Sub-ToDos</relationshipLabel>
    <relationshipName>Sub_ToDos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <description>Something to be done</description>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FutureSubToDoCallouts.cls
public with sharing class FutureSubToDoCallouts {
    @future(callout=true)
    public static void postSubToDo(String subTodoId)
    {
        Sub_ToDo__c subTodo = [SELECT Id, Name, Is_Done__c, ToDo__c  FROM Sub_ToDo__c WHERE Id = :subTodoId];
        // callout post
        String subTodoJson = JSON.serialize(subTodo);
        HttpResponse resp = SubTodoRestCallouts.postSubTodo(subTodoJson);
    }
    @future(callout=true)
    public static void putSubToDo(String subTodoId)
    {
        Sub_ToDo__c subTodo = [SELECT Id, Name, Is_Done__c, ToDo__c  FROM Sub_ToDo__c WHERE Id = :subTodoId];
        // callout put
        String subTodoJson = JSON.serialize(subTodo);
        HttpResponse resp = SubTodoRestCallouts.putSubTodo(subTodoJson);
    }
    @future(callout=true)
    public static void patchSubToDo(String subTodoId)
    {
        Sub_ToDo__c subTodo = [SELECT Id, Name, Is_Done__c, ToDo__c  FROM Sub_ToDo__c WHERE Id = :subTodoId];
        // object serialization
        String subTodoJson = JSON.serialize(subTodo);
        // callout patch
        HttpResponse resp = SubTodoRestCallouts.patchSubTodo(subTodoId, subTodoJson);
    }
    @future(callout=true)
    public static void deleteSubToDo(String subTodoId)
    {
        // callout delete
        HttpResponse resp = SubTodoRestCallouts.deleteSubTodo(subTodoId);
    }
}