force-app/main/default/objects/Sub_ToDo__c/Sub_ToDo__c.object-meta.xml
<CustomObject>
    <description>Subtask for a big task</description>
    <label>Sub-ToDo</label>
    <nameField>
        <label>Sub-ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-ToDos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sub_ToDo__c/fields/Is_Done__c.field-meta.xml
<CustomField>
    <fullName>Is_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mission completed?)</description>
    <label>Is Done</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sub_ToDo__c/fields/ToDo__c.field-meta.xml
<CustomField>
    <fullName>ToDo__c</fullName>
    <description>To which task does</description>
    <label>ToDo</label>
    <referenceTo>ToDo__c</referenceTo>
    <relationshipLabel>Sub-ToDos</relationshipLabel>
    <relationshipName>Sub_ToDos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <description>Something to be done</description>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status can have 3 state</description>
    <inlineHelpText>Please, choose status of yot todo</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to Take</fullName>
                <default>true</default>
                <label>Ready to Take</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public with sharing class TestDataFactory {
    public static List<Id> createTestToDos(Integer numRec) {
        // Create test records
        List<Id> listId = new List<Id>();
        List<ToDo__c> listTodo = new List<ToDo__c>();
        for (Integer i=0;i<numRec;i++) {
            listTodo.add(
                new ToDo__c(
                Name='Test record' + i,
                Status__c='Ready to Take')
            );
        }
        insert listTodo;
        for (ToDo__c td : listTodo) {
            listId.add(td.Id);
        }
        return listId;
    }
    public static List<Id> createTestSubToDos(Integer numRec) {
        // Create test parent ToDo
        ToDo__c todoTest = new ToDo__c(
                Name='Test ToDo',
                Status__c='Ready to Take');
        insert todoTest;
        List<Id> listId = new List<Id>();
        List<Sub_ToDo__c> listSubTodo = new List<Sub_ToDo__c>();
        for (Integer i=0;i<numRec;i++) {
            listSubTodo.add(
                new Sub_ToDo__c(
                Name='Test record' + i,
                Is_Done__c=true,
                ToDo__c=todoTest.Id)
            );
        }
        insert listSubTodo;
        for (Sub_ToDo__c subTd : listSubTodo) {
            listId.add(subTd.Id);
        }
        return listId;
    }
    public static MockHttpResponse createMockHttpResponse(Integer numMock, String strBody) {
        MockHttpResponse mockHttpResponse = new MockHttpResponse();
        for (Integer i = 0; i < numMock; i++) {
            HttpResponse mockRes = new HttpResponse();
            mockRes.setHeader('Content-Type', 'application/json');
            if(strBody != null) {
                mockRes.setBody(strBody);
            }
            mockRes.setStatusCode(200);
            mockHttpResponse.addResponse(mockRes);
        }
        return mockHttpResponse;
    }
}