force-app/main/default/objects/Sub_ToDo__c/Sub_ToDo__c.object-meta.xml
<CustomObject>
    <description>Subtask for a big task</description>
    <label>Sub-ToDo</label>
    <nameField>
        <label>Sub-ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-ToDos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sub_ToDo__c/fields/ToDo__c.field-meta.xml
<CustomField>
    <fullName>ToDo__c</fullName>
    <description>To which task does</description>
    <label>ToDo</label>
    <referenceTo>ToDo__c</referenceTo>
    <relationshipLabel>Sub-ToDos</relationshipLabel>
    <relationshipName>Sub_ToDos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <description>Something to be done</description>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SubToDoControllerTest.cls
@isTest
private with sharing class SubToDoControllerTest {
    private static Integer listSize = 10;
    private static String toDoName = 'ToDo';
    
    @testSetup
    private static void setup() {
        ToDo__c toDo = new ToDo__c(Name = toDoName);
        insert toDo;
        List<Sub_ToDo__c> subToDos = new List<Sub_ToDo__c>();
        for(Integer i = 1; i <= listSize; i++) {
            subToDos.add(new Sub_ToDo__c(Name = 'Sub-ToDo ' + i, ToDo__c = toDo.Id));
        }
        insert subToDos;
    }
    
    @isTest
    private static void getAllSubToDosTest() {
        ToDo__c toDo = [SELECT Id, Name FROM ToDo__c WHERE Name = :toDoName];
        List<Sub_ToDo__c> subToDos = SubToDoController.getAllSubToDos(toDo.Id);
        Test.startTest();
        System.assertEquals(listSize, subToDos.size());
        Test.stopTest();
    }

}