force-app/main/default/objects/Sub_ToDo__c/Sub_ToDo__c.object-meta.xml
<CustomObject>
    <description>Subtask for a big task</description>
    <label>Sub-ToDo</label>
    <nameField>
        <label>Sub-ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-ToDos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sub_ToDo__c/fields/ExtId__c.field-meta.xml
<CustomField>
    <fullName>ExtId__c</fullName>
    <label>ExtId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sub_ToDo__c/fields/Is_Done__c.field-meta.xml
<CustomField>
    <fullName>Is_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mission completed?)</description>
    <label>Is Done</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sub_ToDo__c/fields/ToDo__c.field-meta.xml
<CustomField>
    <fullName>ToDo__c</fullName>
    <description>To which task does</description>
    <label>ToDo</label>
    <referenceTo>ToDo__c</referenceTo>
    <relationshipLabel>Sub-ToDos</relationshipLabel>
    <relationshipName>Sub_ToDos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <description>Something to be done</description>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SubTodoRestCallouts.cls
/**
 * REST callouts
 * for each method of Sub-Todo REST web service from API org
 *
 * @param subTodoJson: serialized object to send
 * in body of  request.
 * Example:
 * String subTodoJson = JSON.serialize([SELECT Id, Name,
 *  Is_Done__c, ToDo__c, ExtId__c
 * FROM Sub_ToDo__c WHERE Id ='********']);
 */

public class SubTodoRestCallouts {

    public static Http http = new Http();
    public static HttpResponse response;
    public static HttpRequest request;

    public static HttpResponse getSubTodo(String id) {
        request = new HttpRequest();
        request.setEndpoint('callout:OrgAPI/services/apexrest/SubTodo/' + id);
        request.setMethod('GET');
        response = http.send(request);
        // System.debug('response.getBody(): ' + response.getBody());
        if(response.getStatusCode() == 200) {
            Sub_ToDo__c subTodo = (Sub_ToDo__c) JSON.deserialize(response.getBody(), Sub_ToDo__c.class);
            // System.debug('subTodo: ' + subTodo);
        }
        return response;
    }
    public static HttpResponse deleteSubTodo(String id) {
        request = new HttpRequest();
        request.setMethod('DELETE');
        request.setEndpoint('callout:OrgAPI/services/apexrest/SubTodo/' + id);
        response = http.send(request);
        // System.debug('response.getBody(): ' + response.getBody());
        if(response.getStatusCode() != 200) {
            System.debug('The status code returned was not expected: ' +
                    response.getStatusCode() + ' ' + response.getStatus());
        }
        return response;
    }
    public static HttpResponse postSubTodo(String subTodoJson) {
        request = new HttpRequest();
        request.setMethod('POST');
        request.setEndpoint('callout:OrgAPI/services/apexrest/SubTodo/');
        request.setHeader('Content-Type', 'application/json;charset=UTF-8');
        request.setBody(subTodoJson);
        response = http.send(request);
        // System.debug('response.getBody(): ' + response.getBody());
        if(response.getStatusCode() != 200) {
            System.debug('The status code returned was not expected: ' +
                    response.getStatusCode() + ' ' + response.getStatus());
        }
        return response;
    }
    public static HttpResponse putSubTodo(String subTodoJson) {
        request = new HttpRequest();
        request.setMethod('PUT');
        request.setEndpoint('callout:OrgAPI/services/apexrest/SubTodo/');
        request.setHeader('Content-Type', 'application/json;charset=UTF-8');
        request.setBody(subTodoJson);
        response = http.send(request);
        // System.debug('response.getBody(): ' + response.getBody());
        if(response.getStatusCode() != 200) {
            System.debug('The status code returned was not expected: ' +
                    response.getStatusCode() + ' ' + response.getStatus());
        }
        return response;
    }
    // for Patch method examples of object serialization:
    // 1) String subTodoJson = '{"name":"1 PATCH TEST JSON","isDone":true}';
    // 2) String subTodoJson = JSON.serialize([SELECT Name, Is_Done__c FROM Sub_ToDo__c WHERE Id
    // = '************']);
    public static HttpResponse patchSubTodo(String subTodoId, String subTodoJson) {
        request = new HttpRequest();
        request.setMethod('PATCH');
        request.setEndpoint('callout:OrgAPI/services/apexrest/SubTodo/' + subTodoId);
        request.setHeader('Content-Type', 'application/json;charset=UTF-8');
        request.setBody(subTodoJson);
        response = http.send(request);
        // System.debug('response.getBody(): ' + response.getBody());
        if(response.getStatusCode() != 200) {
            System.debug('The status code returned was not expected: ' +
                    response.getStatusCode() + ' ' + response.getStatus());
        }
        return response;
    }
}